# Generated by Django 5.1.6 on 2025-03-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Customer',
        ),
    ]
