# Generated by Django 5.1.6 on 2025-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=972592749758, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
