# Generated by Django 5.1.6 on 2025-03-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0002_rename_userprofile_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
