# Generated by Django 5.1.6 on 2025-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0002_order_contact_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
