# Generated by Django 5.1.6 on 2025-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=1111111111111, max_length=13),
            preserve_default=False,
        ),
    ]
