# Generated by Django 5.1.6 on 2025-03-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alnaser', '0004_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
