# Generated by Django 5.1.6 on 2025-03-26 00:17

from django.db import migrations

def set_default_customer(apps, schema_editor):
    Customer = apps.get_model('alnaser', 'Customer')
    Order = apps.get_model('alnaser', 'Order')
    # Get or create a default customer
    default_customer, created = Customer.objects.get_or_create(
        user__username='eyas',
        defaults={...}  # Add other required fields
    )
    # Update all existing orders
    Order.objects.filter(customer__isnull=True).update(customer=default_customer)

class Migration(migrations.Migration):
    dependencies = [
        # Your previous migration
    ]

    operations = [
        migrations.RunPython(set_default_customer),
    ]